title: "Your ping will not improve!"
author:
  name: "Anti-Cheat Team @ Denuvo"
bio: "Denuvo by Irdeto's Anti-Cheat team is located in Wroclaw, Poland and Salzburg, Austria. Its mission is to stealthily detect cheating attempts and provide evidence for best-in-class anti-cheat solutions employed by global gaming customers."
remote_theme: jekyll/minima@v2.5.2

defaults:
  -
    scope:
      path: "ping*"
    values:
      layout: default
      image: https://denuvosoftwaresolutions.github.io/ping-them-all/ping.png
      description: "Unless a serious revolution in physics happens or games put more attention on the importance of server geo-location."

header_pages:
  -

minima:
  # generate social links in footer
  social_links:
    twitter: gamingatdenuvo
    github:  denuvosoftwaresolutions
    linkedincompany: denuvo-gmbh
